services:
  projecta:
    build:
      context: .
      dockerfile: ./AdventureWorksPersistence/Dockerfile
    networks:
      - app-network

  projectb:
    build:
      context: .
      dockerfile: ./WebApplication1/Dockerfile
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "5000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
